services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/usr/src/backend/
    # entrypoint: ["sh", "/usr/src/backend/entrypoint.sh"]
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    environment:
      DATABASE_URL: postgresql://pguser:pguserpassword@db:5432/crud_in_the_cloud_db
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguserpassword
      POSTGRES_DB: crud_in_the_cloud_db
      PGDATA: /var/lib/postgresql/data/

volumes:
  postgres_data: