services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/usr/src/backend/
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev
    environment:
      PYTHONPATH: /usr/src/backend
      DATABASE_URL: postgresql://pguser:pguserpassword@db:5432/crud_in_the_cloud_db
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguserpassword
      POSTGRES_DB: crud_in_the_cloud_db
      PGDATA: /var/lib/postgresql/data/

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@users.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_LISTEN_PORT: 80
      GUNICORN_TIMEOUT: 300
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/pgadmin4/servers.json
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: